name: Generate JSON Data

on:
  push:
    branches: 'main'

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install SQLite
      run: sudo apt-get install sqlite3

    - name: Run script
      run: |
        python race_results.py 'Halloween 10k'
        python race_results.py 'Heart of the Hills Run'
        python race_results.py 'Mystic Mountain Run'
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff --exit-code --quiet || git add . && git commit -m "Workflow: Update JSON data."
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}